### ISSUE TITLE
UrlGenerator problem on Gitlab login

### ISSUE THREAD

**Issue by victorfcm** [renatomarinho/laravel-gitscrum#107]
![captura de tela de 2016-12-26 12-38-34](https://cloud.githubusercontent.com/assets/1637099/21483383/4bdd380a-cb68-11e6-82dd-e5fcd55bbc22.png)

**Comment by renatomarinho** [comment]
Hi, @victorfcm Do you do a pull on the master branch?

**Comment by victorfcm** [comment]
Yeah, I pulled today first in the morning, let'me try again

**Comment by victorfcm** [comment]
Yah, same error :/... 

I've remake my database to test, and anything change, later I'll see if I can solve this :)
