### ISSUE TITLE
Problema ao tentar logar com GitHub e Gitlab

### ISSUE THREAD

**Issue by cesarhgd10** [renatomarinho/laravel-gitscrum#110]
Eu baixei o gitscrum pelo composer e pelo repositório do git, baixou tudo certinho... segui todas as instruções, porém quando eu vou tentar logar pelo Github acontece o seguinte erro:

```
Client error: `GET https://api.github.com/user?access_token=` resulted in a `401 Unauthorized` response:
{
"message": "Bad credentials",
"documentation_url": "https://developer.github.com/v3"
}

```

e quando eu vou tentar logar pelo GitLab:

`The redirect URI included is not valid.`

Eu estou usando o XAMPP com Virtual Host no Ubuntu

essa é a configuração do meu arquivo **.env:**

```
APP_ENV=local
APP_KEY=base64:W2ToyfW8zHqtWfcZb1hp2kZgccbuy3XtERDyZywtVkE=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://gitscrum.local/
APP_TITLE=GitScrum

GITHUB_CLIENT_ID=2f14e2aea90335225d4a
GITHUB_CLIENT_SECRET=3129819a39bfe255775cb3b826cc9a5c70922026

GITLAB_KEY=7c2bfdf4dae8589e7f65b3cb760fa272698a67e46298cbbcd8d609e38791703b
GITLAB_SECRET=610815af83025da8741938b65fb93910a028b4db44b0304b40339e97ce5358b5
GITLAB_INSTANCE_URI=https://gitlab.com/

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=gitscrum
DB_USERNAME=root
DB_PASSWORD=

APP_PAGINATE=10

PROXY_PORT=
PROXY_METHOD=
PROXY_SERVER=
PROXY_USER=
PROXY_PASS=

```

eu já tentei criar várias credenciais pro GitHub e GitLab e mesmo assim não funciona, será que alguém poderia me dar uma ajuda?

Obrigado

**edit:** Essa é a Callback url no GitLab: http://gitscrum.local/auth/login/auth/provider/gitlab/callback

**Comment by renatomarinho** [comment]
Tenta trocar a URL de callback para : http://gitscrum.local/auth/provider/gitlab/callback

**Comment by cesarhgd10** [comment]
Tentei aqui brother, tá dando a mesma coisa

**Comment by cesarhgd10** [comment]
Alguém sabe outra coisa que poderia me ajudar?

**Comment by renatomarinho** [comment]
Please check it https://github.com/renatomarinho/laravel-gitscrum/issues/60

**Comment by cesarhgd10** [comment]
ah, pelo que eu entendi da documentação era pra colocar a url completa no APP_URL no .env. Mas ao trocar` APP_URL=http://gitscrum.local/` para `APP_URL=gitscrum.local/` resolveu o problema
