### ISSUE TITLE
Class 'GitScrum\Classes\Branch' not found

### ISSUE THREAD

**Issue by onecentlin** [renatomarinho/laravel-gitscrum#115]
> Class 'GitScrum\Classes\Branch' not found

![image](https://cloud.githubusercontent.com/assets/7122270/21504877/64dcebd0-cc9d-11e6-8dea-1b46e824649f.png)

Error displayed while adding gitlab repositories to GitScrum -- `wizard/step2`

**Comment by willianmano** [comment]
This was solved in last pr. my mistake
