### ISSUE TITLE
Erro quando chegar em wizard/step1.

### ISSUE THREAD

**Issue by edyonil** [renatomarinho/laravel-gitscrum#133]
![image](https://cloud.githubusercontent.com/assets/1930326/21613027/4823e100-d1b2-11e6-91f9-705860ed18a9.png)

Esse erro ocorre logo depois de chamar a url de callback do login com o gitlab. Aqui nos projetos trabalhamos com opção de Grupos. Quando eu faço o login como administrador não tenho esse erro.

**Comment by edyonil** [comment]
Outra coisa estranha que percebi foi o fato de ele ta usando a classe do Github e não a do Gitlab

**Comment by edyonil** [comment]
Conseguir identifica qual o problema. 

Acontece que, quando entrei pela primeira vez e autorizei o acesso a API, o gitscrum leu todos os usuários do meu gitlab, no entanto, na coluna provider "provider" ele adicionou como github para todos, exceto o meu usuário. 

Para resolver o problema acima, bastar fazer um update:

```sql
update users set provider = 'gitlab';
```

Provavelmente deve ter uma forma de corrigir isso diretamente no código, mas como ainda estou tentando colocar para funcionar o Gitscrum, não pude olhar ainda.

**Comment by renatomarinho** [comment]
@edyonil faz um pull da master e sincroniza novamente. Se precisar de ajuda estou por aqui.

**Comment by edyonil** [comment]
Ola @renatomarinho . Você colocou algo que resolve isso foi? Quando você falar sicronizar é clicar no botão update repositories? Pensei em apagar o banco e rodar as migrations de novos.

Eu vi que você mexeu em algumas classes.

**Comment by willianmano** [comment]
@edyonil Vou verificar isso.

**Comment by edyonil** [comment]
@willianmano blz...

**Comment by willianmano** [comment]
Enviei o PR. O problema é q na hora de salvar não estava sendo enviado o provider. Como o valor default do campo é "github", ele estava salvando com esse valor.

**Comment by renatomarinho** [comment]
@willianmano será que você consegue uma conta no gitlab que tenha projetos para que possamos realizar os testes?

Obs.: Rafatorei um pouco a classe do github, veja a parte das branches e leitura dos repositorios.

**Comment by edyonil** [comment]
Infelizmente a conta que tenho aqui é de repositório local. Não tem como eu disponibilizar.

**Comment by willianmano** [comment]
@renatomarinho eu posso sim criar uma conta e repo pra gente testar no gitlab. Tenho uma instância aqui. Vou providenciar e te passo. Me manda um email ou mensagem no facebook pra eu te passar isso.
