### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by ILunie** [renatomarinho/laravel-gitscrum#141]
<p><strong> For future enhancement </strong></p>
<p>It would be better if this could support a translation of major languages. </p>

**Comment by renatomarinho** [comment]
🥇 Language Support 

Help us to translate
https://github.com/renatomarinho/laravel-gitscrum/tree/feature/language-pack/resources/lang

**Comment by fadynoor** [comment]
is this already translated to Bahasa Indonesia ? if not, i'd like to help

**Comment by jacksun101** [comment]
The link above is not working.
