### ISSUE TITLE
 can't run it 

### ISSUE THREAD

**Issue by LamraniAlaoui** [renatomarinho/laravel-gitscrum#151]
i have this issue, i hope you may help me : 
PHP Fatal error:  Unknown: Failed opening required 'C:\Users\S
EEKER\Desktop\Trabajo\laravel-gitscrum/server.php' (include_path='C:\xampp\php\PEAR') in
Unknown on line 0

**Comment by renatomarinho** [comment]
Hi, you can use docker to run GitScrum. 
https://github.com/renatomarinho/docker-gitscrum

**Comment by LamraniAlaoui** [comment]
thnks
