### ISSUE TITLE
Modificação do tema inspinia

### ISSUE THREAD

**Issue by willianmano** [renatomarinho/laravel-gitscrum#16]
Eu não pude ver todos os assets ainda do sistema, mas ele ta todo em cima do inspinia? Se for é recomendado alterar para um free, visto que o inspinia é pago.

**Comment by renatomarinho** [comment]
@willianmano levanou uma excelente questão, comprei este Inspinia há alguns meses atrás e resolvi aplicar, mas realmente faz sentido um tema free, tem o Gentelella, conhece? https://github.com/puikinsh/gentelella ... Pensou em aplica-lo , alguma outra sugestão?

**Comment by willianmano** [comment]
Não conhecia o gentella... já adicionei nos favoritos. =)

Eu geralmente uso o AdminLTE. https://almsaeedstudio.com/themes/AdminLTE/index2.html
