### ISSUE TITLE
ErrorException in IssueObserver.php line 38

### ISSUE THREAD

**Issue by zakiaziz** [renatomarinho/laravel-gitscrum#163]
<p>One Wizard step 3 I get this error: <code>ErrorException in IssueObserver.php line 38:</code>
<img src="https://cloud.githubusercontent.com/assets/940281/23007160/a64af0ea-f3d4-11e6-9664-37c65c2e79b6.png" alt="screen shot 2017-02-15 at 11 15 01 pm" /></p>

**Comment by zakiaziz** [comment]
Hi, I'm assuming you won't be helping with this issue?

**Comment by JelleDijkhuizen** [comment]
did you try updating to the latest version?
