### ISSUE TITLE
SocialiteProviders\GitLab\Provider::getAccessTokenResponse() error

### ISSUE THREAD

**Issue by guetteman** [renatomarinho/laravel-gitscrum#166]
Hi!

I've found an error on GitLab Socialite provider, it cannot find **getAccessTokenResponse()** method. I've check the **Laravel\Socialite\Two\AbstractProvider** and I found **getAccessToken()** method.

I think SocialiteProviders/GitLab is not working with Laravel 5.4. Can you help me?

**Comment by JelleDijkhuizen** [comment]
I think it is becaue of the wrong version of laravel/socialite. It's using dev-master but we need the 3.0 branch.
I think this because of this: This branch is 149 commits behind 3.0.

Trying to find a way to fix this problem

**Comment by JelleDijkhuizen** [comment]
Got it working again.
First in composer.json change minimum-stability to stable.
Than run composer update.
After that run: php artisan view:clear and you're good to go

**Comment by guetteman** [comment]
Now it's working, thanks!
