### ISSUE TITLE
not able to login to the project

### ISSUE THREAD

**Issue by rjsnh1522** [renatomarinho/laravel-gitscrum#173]
<p>I tried everything which is mentioned in the readme but still I am not able to login to the project with github</p>
<p><img src="https://cloud.githubusercontent.com/assets/7428293/23581518/8465687e-013b-11e7-9504-81b4f0453215.jpg" alt="17098383_1283509838409355_4135263337249650834_n" />
<img src="https://cloud.githubusercontent.com/assets/7428293/23581521/890ef9f8-013b-11e7-9ef7-b6cd5938e82d.jpg" alt="17098722_1283511051742567_1005178691507545333_n" />
see the images . and please help me to run the project in local so that i can test it and learn from it please.</p>

**Comment by rjsnh1522** [comment]
now I am getting this error 
![image](https://cloud.githubusercontent.com/assets/7428293/23581856/7b9ffea4-0143-11e7-92ee-cf2fdd4c792f.png)

**Comment by platedodev** [comment]
Check those fields on your .env

> GITHUB_CLIENT_ID=XXXXX
GITHUB_CLIENT_SECRET=XXXXXXXXXXXXXXXXXX

**Comment by rjsnh1522** [comment]
they are correct  have copied that from github when i created the app for logging in github using gitscrum

**Comment by renatomarinho** [comment]
@rjsnh1522 check it : https://github.com/renatomarinho/laravel-gitscrum/issues/110 OR https://github.com/renatomarinho/laravel-gitscrum/issues/60

**Comment by rjsnh1522** [comment]
not helped #110 i dont understand the language.. in #60 i tried removing http:// from app_url in .env file but it didnt worked

**Comment by renatomarinho** [comment]
Try create a new application on GitHub and after add new credentials in .env file.

Important: url for callback is you URL local

**Comment by rjsnh1522** [comment]
APP_URL=http://localhost/scru/public/auth/login

call back url in my github app is
http://localhost/scru/public/auth/provider/github/callback

is this the wrong way... one more question when i go to my project 
http://localhost/scru/ i see the folder structure .. then i go to my public folder then only i see the first page of project.. can u tell me how to start my project from direct project name 
like http://localhost/scru/ 

please

**Comment by renatomarinho** [comment]
Try change your VirtualHost on Apache, DocumentRoot should be something it "/www/gitscrum/public".

If you prefer, GitScrum have a environment using Docker. See https://github.com/renatomarinho/docker-gitscrum

**Comment by rjsnh1522** [comment]
can u explain a bit more about virtual host.? I m running this on windows 10.

**Comment by renatomarinho** [comment]
kjhlhjkljhk
