### ISSUE TITLE
Group namespace error

### ISSUE THREAD

**Issue by theminer3746** [renatomarinho/laravel-gitscrum#178]
I'm setting up gitscrum and after I config everything (Database, github token, folder permission etc.) I got this error
![untitled](https://cloud.githubusercontent.com/assets/9322228/23587339/8029a10c-01dc-11e7-87b2-31fb4493a260.png)

I know group namespace came out in php 7 so I verify with `php -v` in command line and display `phpinfo()`.
My php version (from `phpinfo()`) is `7.0.16-4+deb.sury.org~xenial+1` using `FPM/FastCGI` as API
I'm running on Ubuntu 16.04 and nginx 1.10.0

P.S. Line 12 is `use {Request,Session,Auth};`
And comment that line out and use
```
use Request;
use Session;
use Auth;
```
seems to work.

Any idea?
Thanks in advance.

**Comment by renatomarinho** [comment]
@theminer3746 yes, that commit fixed it https://github.com/renatomarinho/laravel-gitscrum/commit/c0ad42907c9421bd315ca83ffe32e6e674ce5278 .. please do a new pull
