### ISSUE TITLE
Rodar localmente

### ISSUE THREAD

**Issue by paulodealmeida** [renatomarinho/Laravel-GitScrum#18]
Tem como rodar localmente sem a autenticação no github?

**Comment by willianmano** [comment]
Não é possivel. Muitas regras são ligadas diretamente ao github, como por exemplo organizações, repositórios e etc...

**Comment by paulodealmeida** [comment]
No campo "Homepage URL" devo colocar uma url válida de uma página no ar?

**Comment by willianmano** [comment]
Deve coloar a URL que está rodando seu APP. O meu local, por exemplo está em localhost, então o APP_URL=localhost. Mas pode ser várias coisas:

APP_URL=localhost

APP_URL=localhost:8080

APP_URL=localhost/meuapp

APP_URL=meuapp.dev

**Comment by paulodealmeida** [comment]
Funcionou, valeu @willianmano
