### ISSUE TITLE
Remover chamada desnecessária ao github ao acessar o dashboard

### ISSUE THREAD

**Issue by guilhermeof** [renatomarinho/laravel-gitscrum#21]
Toda vez ao acessar o DashBoard a aplicação está indo no GitHub e trazendo os repositórios e tentando salvar os mesmos.

**Comment by marcosrjjunior** [comment]
Esse 'carregamento automatico' também estava afetando e muito na autenticação do usuário.

Enviei um ajuste simples, direcionando a atualização dos repositórios para uma ação no próprio dashboard, até que se possa pensar em uma maneira melhor.

**Comment by willianmano** [comment]
Eu acredito que é uma boa abordagem é pegar todos os repos e organizações no registro e remover a busca em todo o login.

Adicionaria então algum área no perfil com a opção sincronizar informações com o github.
