### ISSUE TITLE
sprints/list

### ISSUE THREAD

**Issue by Datazource** [renatomarinho/laravel-gitscrum#212]
i got this error while go here `sprints/list`

![alt text](https://preview.ibb.co/d6Fnvk/asd.png "Logo Title Text 1")

ubuntu 16.0.4
mysql 5.7
php 7.1
laravel 5.4

and i got severals `Trying to get property of non-object`, such as here : `notes/store`

**Comment by Te7a-Houdini** [comment]
@Datazource  try to run the seeders  `php artisan db:seed --class=SettingSeeder`

**Comment by JorRaf** [comment]
[ReflectionException]
Class SettingSeeder does not exist

How to fix it?

**Comment by Datazource** [comment]
If the class is exists under the database folders, then u just need to run `php artisan optimize` or `composer dump-autoload`
