### ISSUE TITLE
Sprint view problem 

### ISSUE THREAD

**Issue by mckilleron** [renatomarinho/laravel-gitscrum#31]
When i try to view a sprint content : 

SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(*) as aggregate from `issues` where `issues`.`sprint_id` = 2 and `issues`.`sprint_id` is not null and date(`closed_at`) = 2016-12-01 and `issues`.`deleted_at` is null order by `position` asc) (View: C:\xampp7\htdocs\laravel-gitscrum\resources\views\sprints\show.blade.php)

**Comment by bagaskarawg** [comment]
Maybe it has something to do with your version of MySQL?

**Comment by mckilleron** [comment]
I'm on MariaDB

**Comment by mckilleron** [comment]
Ok i've solved, i've modified config/database.php and modify mysql strict ==> False;
