### ISSUE TITLE
Can this work with GITLAB

### ISSUE THREAD

**Issue by vik0803** [renatomarinho/laravel-gitscrum#34]
Hi,

Quick Question: Can this work with Gitlab or Gitamin as well same as GITHUB?

**Comment by ganjarsetia** [comment]
+1

**Comment by renatomarinho** [comment]
yet not, but is on roadmap it integration

**Comment by victorfcm** [comment]
I already started the GitLab integration, Socialite Proviter to GitLab : http://socialiteproviders.github.io/providers/gitlab/

I'll add this in the first 15 days of 2017 :)

**Comment by dakira** [comment]
Don't forget the wonderful Gogs. ;)

**Comment by victorfcm** [comment]
Work in progress at #77 :)

**Comment by victorfcm** [comment]
#79 PR @ develop branch.
