### ISSUE TITLE
Error on sprint details screen

### ISSUE THREAD

**Issue by cristianvuolo** [renatomarinho/laravel-gitscrum#39]
![image](https://cloud.githubusercontent.com/assets/2281424/21117827/7bfb35a8-c0a2-11e6-837c-9ffa7043b31d.png)

Am I doing something wrong?

**Comment by renatomarinho** [comment]
Are you using mariadb? Change in .env file the connection to use mariadb.

**Comment by cristianvuolo** [comment]
Perfeito (y) valeu pela ajuda!

**Comment by yinx** [comment]
This is most likely the same error I found.
I have made a pull request that fixes it.
