### ISSUE TITLE
Migrations Failed

### ISSUE THREAD

**Issue by caktoy** [renatomarinho/laravel-gitscrum#41]
Hi, I would to try this system, but when I try to migrate the database, I have an error like this, can you help me?
![image](https://cloud.githubusercontent.com/assets/6917446/21128351/c47d5880-c12c-11e6-9a46-e5806352882f.png)

**Comment by yinx** [comment]
Can you post an image of your db settings?
The most likely reason is you accidentally added the wrong values.

**Comment by caktoy** [comment]
this is my database.php file:
![image](https://cloud.githubusercontent.com/assets/6917446/21152975/2f4b1ec2-c19b-11e6-9806-ba63ac7d51be.png)

this is my .env file:
![image](https://cloud.githubusercontent.com/assets/6917446/21152998/3caa50c4-c19b-11e6-9be9-4767b7592127.png)

**Comment by yinx** [comment]
That seems ok. U assume you're using a local database?
Did you check your db name and are you Sure you haven't set a password?

Hope this helps!

**Comment by caktoy** [comment]
I didn't set my local database password, so I set my password for the database setting to empty. Do I have to give a password on my local database?

I was did composer update to this, everything is fine, here you can look at the result:
![image](https://cloud.githubusercontent.com/assets/6917446/21210662/73ccb67c-c2af-11e6-8885-7ea37878a5b2.png)
Is something wrong and what should I do?
