### ISSUE TITLE
Add Some Tests

### ISSUE THREAD

**Issue by jonasporto** [renatomarinho/laravel-gitscrum#5]
It would be interesting add some test coverage to keep the functionalities working correctly throughout the project evolution.

**Comment by yinx** [comment]
I assume this means something along the lines of "Add some tests".
If so I completely agree.
When I get some more time I'll probably look into creating a PR with some tests to get the ball rolling.

**Comment by jonasporto** [comment]
yes, you got @yinx =)
I'll update to english, sorry for that.
