### ISSUE TITLE
Typo(s?) in readme

### ISSUE THREAD

**Issue by jamesaspence** [renatomarinho/laravel-gitscrum#52]
Hello,

I noticed at least one typo in the readme. Assuming this readme is static (not sure if it's auto-generated from somewhere), I could fix it? Just curious how / if the readme is generated, otherwise I'll create a PR to fix the typo :)

**Comment by renatomarinho** [comment]
the readme is static, you can fix and create a PR. :)

**Comment by jamesaspence** [comment]
Sounds good! Thank you.
