### ISSUE TITLE
Install in 5.1 ?

### ISSUE THREAD

**Issue by chaibialaa** [renatomarinho/laravel-gitscrum#54]
Hello,

Is there any ability to run this in a 5.1 Laravel version ? 

Thank you (my server is limited to php 5.6)

**Comment by renatomarinho** [comment]
Hi, you can run with php 5.6. The GitScrum is using Laravel 5.3.

**Comment by chaibialaa** [comment]
The laravel 5.3 is using php 7 :)

**Comment by renatomarinho** [comment]
You can use php 5.6 , php 7 or hhvm
