### ISSUE TITLE
How to close Sprints?

### ISSUE THREAD

**Issue by bfgasparin** [renatomarinho/laravel-gitscrum#55]
How can I close an Sprint?

I tested GitScrum and I liked it a lot. I created some sprints, with their user stories and issues, but I can`t figure out how to close old expired Sprints.

Old Sprints (expired), sprints with all issues marked as `done`, all of them remains open into the system. How to close them?

**Comment by yinx** [comment]
@bfgasparin You can remove a sprint by clicking the trashcan icon.
![image](https://cloud.githubusercontent.com/assets/1022847/21177638/52a9e244-c1ec-11e6-9d20-47c234053f4e.png)

**Comment by victorfcm** [comment]
Yeah, but, remove a sprint is not close it, I think that sprint closing should be a feature :)
