### ISSUE TITLE
Composer Install is not working 

### ISSUE THREAD

**Issue by lukepolo** [renatomarinho/laravel-gitscrum#56]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

                                                              
  [Symfony\Component\Debug\Exception\FatalThrowableError]     
  Class 'Way\Generators\GeneratorsServiceProvider' not found

**Comment by renatomarinho** [comment]
use: composer update
