### ISSUE TITLE
Can't login Github

### ISSUE THREAD

**Issue by insanrizky** [renatomarinho/laravel-gitscrum#60]
![screen shot 2016-12-14 at 09 34 43](https://cloud.githubusercontent.com/assets/8219655/21168040/96c08b3a-c1e3-11e6-82f8-e2a6c608a861.png)

I have created my Github OAuth Application and put the **CLIENT ID & SECRET ID** to my **.env** file.. I also have set virtual host in my local, so my laravel-gitscrum can accessed by **laravel.gitscrum.local**.. But when i tried to login github on route **/auth/github**, it was happened..

Can anyone help me, please?

**Comment by renatomarinho** [comment]
@insanrizky try create a new application. I did a test and when changes the GITHUB_CLIENT_SECRET to wrong, displays the same error.

Follow it https://github.com/renatomarinho/laravel-gitscrum#github-application

**Comment by insanrizky** [comment]
oh.. i got it.. the problem is i put **http://** prefix on my **APP_URL** in .env file.. when i removed it, all was running as well..

 thanks @renatomarinho ..

**Comment by renatomarinho** [comment]
Do a new pull, you need get it https://github.com/renatomarinho/laravel-gitscrum/commit/2ab5c950cdb76843716d903b7bf8d0b051ebf0c6#diff-3e07726e9e54a0f0d14991172124bb00R26
