### ISSUE TITLE
Empty repository list

### ISSUE THREAD

**Issue by victorfcm** [renatomarinho/laravel-gitscrum#62]
In /wizard/step1, my list of repositories is empty, but in fact, i've some repos in my profile, what could it be?

**Comment by renatomarinho** [comment]
Hi @victorfcm , you can send return of the method : app('GithubClass')->readRepositories()

**Comment by victorfcm** [comment]
```
object(Illuminate\Support\Collection)[433]
  protected 'items' => 
    array (size=0)
      empty
```
:/

**Comment by victorfcm** [comment]
Okay, i got the error, I'm behind a proxy server, so in the "request()" function i added the CURL options to run behind it, and now it works.

I'll add proxies configs to the .env and get then in this file, later i'll make a PR about it

**Comment by victorfcm** [comment]
#65 solve this :)
