### ISSUE TITLE
RequestException in CurlFactory.php line 187: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by raingrave** [renatomarinho/laravel-gitscrum#66]
![print](https://cloud.githubusercontent.com/assets/7664686/21207470/6917add2-c24f-11e6-9582-6a0c45fe48bb.png)

**Comment by raingrave** [comment]
Resolvido!

https://laracasts.com/discuss/channels/laravel/how-to-solve-curl-error-60-ssl-certificate-in-laravel-5-while-facebook-authentication

**Comment by renatomarinho** [comment]
Nice!
