### ISSUE TITLE
Can't connect to application

### ISSUE THREAD

**Issue by mckilleron** [renatomarinho/laravel-gitscrum#69]
I've pull and now I have, before the pulling, it's worked :

![image](https://cloud.githubusercontent.com/assets/23717316/21218939/f6e70b04-c2b2-11e6-9c10-d9c264899ebf.png)

![image](https://cloud.githubusercontent.com/assets/23717316/21218944/fc31d4c2-c2b2-11e6-9053-ab74870936ed.png)

![image](https://cloud.githubusercontent.com/assets/23717316/21218996/2d771524-c2b3-11e6-95c5-70a0aa134fef.png)

**Comment by victorfcm** [comment]
on "APP_URL" config, try to put http://localhost/

**Comment by mckilleron** [comment]
Fixed, but working yesterday
