### ISSUE TITLE
Work in progress, login with GitLab 

### ISSUE THREAD

**Issue by victorfcm** [renatomarinho/laravel-gitscrum#77]
You can see the initial commit here:
https://github.com/victorfcm/laravel-gitscrum/commit/c755a9532379948005cb7d0657c9764a7044aca6

The login is working fine, just need now to get the data and build the UserModel with the info.

I belive i'll finish this before the new year :)

**Comment by victorfcm** [comment]
The only change needed to GitHub work with this changes is the callback URL config on the app, must be /auth/provider/github/callback and not /auth/github/callback anymore :)

**Comment by renatomarinho** [comment]
wowwww it is great!!!!

**Comment by renatomarinho** [comment]
Do a PR

**Comment by victorfcm** [comment]
Done #79 :)
