### ISSUE TITLE
Problema com as organizações

### ISSUE THREAD

**Issue by willianmano** [renatomarinho/Laravel-GitScrum#9]
Não são carregadas as organizações do usuário na hora de se criar um product backlog.

**Comment by renatomarinho** [comment]
@willianmano faz um pull e efetue o login novamente, veja se as organizações estão na base de dados corretamente. aguardo

**Comment by marcosrjjunior** [comment]
Provavelmente porque a organização deve estar privada para esse usuário.
http://github.com/orgs/SLUGDAORGANIZAO/people. 
Verifique a situação do usuário na organização pelo link acima.

**Comment by willianmano** [comment]
Não foi isso não @marcosrjjunior . @renatomarinho Aparentemente agora está tudo correto. Instalei do zero e carregou todas as instituições e repositórios e users. Porém o único user que tem vínculo com a organização é o que está se cadastrando.
