### ISSUE TITLE
Add Pagination

### ISSUE THREAD

**Issue by alfa6661** [renatomarinho/laravel-gitscrum#91]
I'm trying to add repositories into the Gitscrum.
i have more than 30 repositories and i can't add another repositories on the next page because it only return 30 records per page.

When the API returns more than 30 repositories, it should be able to fetch next pages.

---

something like:

https://github.com/renatomarinho/laravel-gitscrum/blob/b54c7736f02363e5c43802a2caa88ea517db570d/app/Classes/Github.php#L84

```php
$repos = collect(Helper::request('https://api.github.com/user/repos?page=n'));
```

**Comment by renatomarinho** [comment]
I will fix it

**Comment by renatomarinho** [comment]
fixed
