### ISSUE TITLE
Problem when login with gitlab

### ISSUE THREAD

**Issue by willianmano** [renatomarinho/laravel-gitscrum#95]
There is an error when try to connect with gitlab. In the gitlab auth provider is called an object *owner* from the repo, but gitlab does permit access to it. I'm trying to solve that but need to study more the app structure. Renato, if you desire i can create an gitlab account for you to test.

![screenshot from 2016-12-23 12-48-06](https://cloud.githubusercontent.com/assets/233643/21457470/50e5f19a-c90e-11e6-85f0-cca0e4304a8a.png)

**Comment by willianmano** [comment]
I'm using groups in this gitlab instance. So, the owner object is null but the namespace not. I think we just need to get the infos from namespace instead of owner.

**Comment by victorfcm** [comment]
i'll see this later this week :)

**Comment by willianmano** [comment]
I just solved right now. Sending PR in a few minutes...
